### ISSUE TITLE
unidbf-server跑久了cpu一直高涨，请问怎么解决

### ISSUE THREAD

**Issue by feng504x** [anjia0532/unidbg-boot-server#10]
unidbf-server跑久了cpu一直高涨，请问怎么解决

**Comment by anjia0532** [comment]
参考 https://github.com/anjia0532/unidbg-boot-server/blob/main/QA.md#unidbgserver%E8%BF%90%E8%A1%8C%E4%B8%80%E6%AE%B5%E6%97%B6%E9%97%B4%E5%90%8E%E6%8B%92%E7%BB%9D%E6%9C%8D%E5%8A%A1%E6%88%96%E6%97%A0%E5%93%8D%E5%BA%94
