### ISSUE TITLE
大神，Log输出文件该怎么设置才是正确的？

### ISSUE THREAD

**Issue by zhucan3n** [anjia0532/unidbg-boot-server#12]
大神，我把两个Log文件都设置了，但是运行单页代码还是输出很多？是我输出错误吗？我把所有都设置成OFF了。
但是还是输出很多。

**Comment by anjia0532** [comment]
你是怎么运行的？

**Comment by zhucan3n** [comment]
直接在sever里面右键运行的。

**Comment by anjia0532** [comment]
直接运行的 这个 https://github.com/anjia0532/unidbg-boot-server/blob/main/src/main/java/com/anjia/unidbgserver/UnidbgServerApplication.java？
https://github.com/anjia0532/unidbg-boot-server/blob/main/src/main/resources/logback-spring.xml 改的这个文件？

java里的log4j 和logback 是基于包名控制日志级别的。你看看你打日志的包在不在这个文件里。
