### ISSUE TITLE
你好，logdebug之后如何设置成可在控制台输入？

### ISSUE THREAD

**Issue by NiceNainai** [anjia0532/unidbg-boot-server#13]
我发现把logger name="com.github.unidbg" 设置了DEBUG后。在控制台是只读模式。
我想输出bt去获得堆栈，但是无法做到。
我在原来的unidbg可以输入，所以我想咨询你下这个问题该怎么解决。

`2022-11-19 21:44:45.639 DEBUG 12684 --- [           main] c.g.unidbg.linux.android.dvm.DalvikVM    : ReleaseStringUTFChars string="0093CB6721DAF15D31CFBC9BBE3A2B79", pointer=RW@0x40172000, lr=RX@0x40000a9b[libwtf.so]0xa9b
2022-11-19 21:44:45.639 DEBUG 12684 --- [           main] com.github.unidbg.spi.AbstractLoader     : munmap aligned=0x1000, start=0x40172000, base=0x40172000, size=4096
2022-11-19 21:44:45.643  WARN 12684 --- [           main] c.github.unidbg.arm.AbstractARMEmulator  : Read memory failed: address=0x40172000, size=4, value=0x0, PC=RX@0x4003fc90[libc.so]0x18c90, LR=RX@0x40061b17[libc.so]0x3ab17
debugger break at: 0x4003fc90 @ Function32 address=0x40000931, arguments=[unidbg@0xfffe12a0, 1050058429, 503427379, 640294829, 1810273055]
>>> r0=0x40172000 r1=0x40172000 r2=0xffffffff r3=0x0 r4=0x2 r5=0xbfffed18 r6=0xccccccc r7=0x0 r8=0xbffff654 sb=0x0 sl=0x40172000 fp=0xbffff658 ip=0x4009d7d0
>>> SP=0xbfffec10 LR=RX@0x40061b17[libc.so]0x3ab17 PC=RX@0x4003fc90[libc.so]0x18c90 cpsr: N=0, Z=1, C=1, V=0, T=1, mode=0b10000
>>> d0=0x0(0.0) d1=0x0(0.0) d2=0x3937423241334536(4.479439438725677E-33) d3=0x3431323236333632(2.739493383241826E-57) d4=0x2030203020302030(1.2027122125173386E-153) d5=0x2030203020302030(1.2027122125173386E-153) d6=0x2030203020302030(1.2027122125173386E-153) d7=0x2030203020302030(1.2027122125173386E-153)
>>> d8=0x0(0.0) d9=0x0(0.0) d10=0x0(0.0) d11=0x0(0.0) d12=0x0(0.0) d13=0x0(0.0) d14=0x0(0.0) d15=0x0(0.0)
strlen + 0x0
=> *[libc.so     *0x18c91]*[90f800f0]*0x4003fc90:*"pld [r0]"
    [libc.so      0x18c95] [0146    ] 0x4003fc94: "mov r1, r0"
    [libc.so      0x18c97] [10f00703] 0x4003fc96: "ands r3, r0, #7"
    [libc.so      0x18c9b] [1dd0    ] 0x4003fc9a: "beq #0x4003fcd8"
    [libc.so      0x18c9d] [c3f10803] 0x4003fc9c: "rsb.w r3, r3, #8"
    [libc.so      0x18ca1] [5feac37c] 0x4003fca0: "lsls.w ip, r3, #0x1f"
    [libc.so      0x18ca5] [02d0    ] 0x4003fca4: "beq #0x4003fcac"
    [libc.so      0x18ca7] [11f8012b] 0x4003fca6: "ldrb r2, [r1], #1"
    [libc.so      0x18cab] [42b3    ] 0x4003fcaa: "cbz r2, #0x4003fcfe"
    [libc.so      0x18cad] [08d3    ] 0x4003fcac: "blo #0x4003fcc0"
    [libc.so      0x18caf] [13f0020c] 0x4003fcae: "ands ip, r3, #2"
    [libc.so      0x18cb3] [05d0    ] 0x4003fcb2: "beq #0x4003fcc0"
    [libc.so      0x18cb5] [11f8012b] 0x4003fcb4: "ldrb r2, [r1], #1"
    [libc.so      0x18cb9] [0ab3    ] 0x4003fcb8: "cbz r2, #0x4003fcfe"
    [libc.so      0x18cbb] [11f8012b] 0x4003fcba: "ldrb r2, [r1], #1"
    [libc.so      0x18cbf] [f2b1    ] 0x4003fcbe: "cbz r2, #0x4003fcfe"

`

//后续就无法输入了,显示只读模式。

**Comment by anjia0532** [comment]
一般用unidbg boot server 的是为了对外提供http服务，也就是作为一个 api 服务器来用。这种情况下不会有debug调试的需求啊。别人访问一次 api，卡主了，你这边再手动输入一个指令，给那边返回结果么？早就超时了。

更适合你的是Junit test的方式 https://github.com/anjia0532/unidbg-boot-server/blob/main/src/test/java/com/anjia/unidbgserver/RegisterNativeTest.java

**Comment by NiceNainai** [comment]
我是在单元测试的时候调试的。

**Comment by anjia0532** [comment]
这个我没用过，估计是 unidbg 用的在springboot test 里不支持，参考 https://stackoverflow.com/questions/31635698/junit-testing-for-user-input-using-scanner

**Comment by anjia0532** [comment]
从网上找了个demo，可以 `HookByConsoleDebugger`
![image](https://user-images.githubusercontent.com/15098916/202944716-21437619-b0de-44c5-9e99-9794a075baf8.png)

[LingLingBangTest.zip](https://github.com/anjia0532/unidbg-boot-server/files/10051889/LingLingBangTest.zip)

**Comment by NiceNainai** [comment]
谢谢博主，我发现新建一个类就可以实现我的问题啦 。直接在类中调用就可以了。
问一下博主，这个在怎么样可以获得？
https://github.com/anjia0532/unidbg-boot-server/issues/1

**Comment by anjia0532** [comment]
现在就有啊，https://github.com/anjia0532/unidbg-boot-server/blob/main/src/test/java/com/anjia/unidbgserver/AutoGeneratorTest.java

**Comment by NiceNainai** [comment]
哇。博主厉害！！！
还有博主，比如我想修改unidbg库里面的ARM64SyscallHandler.class东西。
但是它为只读状态，我可以怎么操作它？让他能编辑呢？

**Comment by anjia0532** [comment]
这事你应该去上游 unidbg 问
