### ISSUE TITLE
大佬你好，补环境的情况下重写方法只执行一次

### ISSUE THREAD

**Issue by sry4leave6** [anjia0532/unidbg-boot-server#15]
@Override
    public DvmObject<?> callObjectMethodV(BaseVM vm, DvmObject<?> dvmObject, String signature, VaList vaList) {

        switch (signature) {
            case "android/content/Context->getPackageName()Ljava/lang/String;":
                StringObject stringObject = new StringObject(vm, appPkgName);
                return stringObject;
//                return new StringObject(vm, vm.getPackageName());
        }
        return super.callObjectMethodV(vm, dvmObject, signature, vaList);
    }

大佬你好  我想通过post传递参数进来执行，启动服务后执行第一次的时候这个重写的方法会执行，后续再传的时候就无效了，请问有什么解决办法吗，感谢

**Comment by anjia0532** [comment]
加个成员变量（不懂百度搜 `java 成员变量` ） 默认是false，第一次时，判断，如果是false，执行初始化，然后改成true，那么后边再执行，因为是true，所以不再执行，下次重启，第一次还是false满足你的需求

**Comment by sry4leave6** [comment]
感谢大佬的关注，我的目的是想通过post传入包名，在补环境的时候动态的使用传入的包名。遇到的困难是，第一次传入的时候确实是成功的使用了传入的包名，再次请求的时候无论传入什么包名都是按照第一次传入的包名环境在运行，重写的callObjectMethodV这类的方法也没有再执行。

**Comment by sry4leave6** [comment]
好的，谢谢大佬，我琢磨琢磨其他方案
