### ISSUE TITLE
提一个修改小建议

### ISSUE THREAD

**Issue by 1273082756** [anjia0532/unidbg-boot-server#20]
分享一个高并发下会报错的写法
![image](https://github.com/anjia0532/unidbg-boot-server/assets/42940500/b5758e99-1234-4b4d-916a-dee5bbb249d5)
![image](https://github.com/anjia0532/unidbg-boot-server/assets/42940500/00420c68-63f2-40cf-b097-56455eb6b634)
这个地方这样写会更好一点
![image](https://github.com/anjia0532/unidbg-boot-server/assets/42940500/39e8d8c2-2b03-4b2d-902a-04e4c95a3d00)

**Comment by anjia0532** [comment]
你这样容易爆内存，第一次写是当作成员变量用，就是new一次，后边一直用，第二种你所谓的高并发好用本质上就是每次new新对象，如果没有调用释放的话，容易爆内存。

我原本的写法是，跟你写成员变量(第一种写法)类似，初始化一次。
https://github.com/anjia0532/unidbg-boot-server/blob/759d62bfdb3c0edd2c43b580302299cbf4305b1f/src/main/java/com/anjia/unidbgserver/web/TTEncryptController.java#L24-L25

你试试把线程池调大试试？跟你每次一new类似。
https://github.com/anjia0532/unidbg-boot-server/blob/759d62bfdb3c0edd2c43b580302299cbf4305b1f/src/main/resources/application.yml#L15-L21
