### ISSUE TITLE
打包成jar后, 在win10/11以java命令行运行jar, 遇到中文的时候会出现一些乱码, idea运行不会出现该问题

### ISSUE THREAD

**Issue by 1273082756** [anjia0532/unidbg-boot-server#23]
环境: win10/11 jdk8
打包命令 .\mvnw.cmd package -T10 -DskipTests
运行命令 java -jar target\unidbg-boot-server-0.0.1-SNAPSHOT.jar
效果图
![image](https://github.com/user-attachments/assets/6a6228de-e82f-4de7-a9c9-861c204dd920)

**Comment by anjia0532** [comment]
控制台字符集的问题。如果你不是非得从控制台看输出（比如通过日志文件看），那啥也不影响。或者百度 `maven 乱码`
