### ISSUE TITLE
运行报错：Illegal JNI version: 0xffffffff

### ISSUE THREAD

**Issue by MrZsy** [anjia0532/unidbg-boot-server#27]
项目在unidbg 0.9.8 版本下正常运行，移植到unidbg-boot-server下报错：
Constructor threw exception; nested exception is java.lang.IllegalStateException: Illegal JNI version: 0xffffffff

**Comment by anjia0532** [comment]
换成0.9.7试试，readme 不是说了吗，目前只支持0.9.7，,0.9.8没试过。

**Comment by MrZsy** [comment]
单独使用 0.9.7 版本也可以正常运行

**Comment by anjia0532** [comment]
我是说，你移植到unidbg-boot-server后，用0.9.7的跑下看看。如果还报错，试试别用多线程，改用单线程，或者直接每次new对象看看。你啥啥啥信息都没有（比如apk，以及对应的方法），没法说。另外我已经很近没用unidbg了。
