### ISSUE TITLE
Docker 打包时，使用方案一报错

### ISSUE THREAD

**Issue by Dreamcatcher9009** [anjia0532/unidbg-boot-server#7]
# 方案1 打包并发布到docker hub
mvn clean package -Djib.to.auth.username=your_docker_hub_username  -Djib.to.auth.password=your_docker_hub_password -Djib.to.image=your_docker_hub_username/unidbg-boot-server  jib:build -Dmaven.test.skip=true --batch-mode -T4

报错如下：
[ERROR] /root/Desktop/unidbg-boot-server/src/main/java/com/anjia/unidbgserver/service/TTEncryptService.java:[34,19] reference to Module is ambiguous
  both class com.github.unidbg.Module in com.github.unidbg and class java.lang.Module in java.lang match
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.885 s (Wall Clock)
[INFO] Finished at: 2022-06-24T16:02:59+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project unidbg-boot-server: Compilation failure
[ERROR] /root/Desktop/unidbg-boot-server/src/main/java/com/anjia/unidbgserver/service/TTEncryptService.java:[34,19] reference to Module is ambiguous
[ERROR]   both class com.github.unidbg.Module in com.github.unidbg and class java.lang.Module in java.lang match
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by anjia0532** [comment]
```
[ERROR] /root/Desktop/unidbg-boot-server/src/main/java/com/anjia/unidbgserver/service/TTEncryptService.java:[34,19] reference to Module is ambiguous
both class com.github.unidbg.Module in com.github.unidbg and class java.lang.Module in java.lang match
```
写的很明白啊

**Comment by Dreamcatcher9009** [comment]
壮强已经收到你的邮件，谢谢！
